[paths]
# IF126: 納入日程管理（正）
IF126_TEMPLATE = K:\\PW_Tableau\\IF126_納入日程管理\\NHSAPOTHIF126_{yyyymmdd}.txt

# IF130: MRP警告リスト
IF130_TEMPLATE = K:\\PW_Tableau\\IF130_MRP警告リスト\\NHSAPOTHIF130_{yyyymmdd}.txt

[encoding]
file = cp932

[server]
HOST = 0.0.0.0
PORT = 5000
